from cgitb import reset
import json
from random import random
import uuid
from elasticsearch import Elasticsearch, helpers

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "NLQOcsuetKM6tWSkZ8pTTloZ"

# Found in the 'Manage Deployment' page
CLOUD_ID = "SIH:YXAtc291dGgtMS5hd3MuZWxhc3RpYy1jbG91ZC5jb206NDQzJDE0Mjc3ODcwNDgwYTQ5NmI5OTc2MDlhODIzN2UwYjY1JGUxOGQ1OTEzNDU3NjQ3OTBhYTY3NzcyNDc1YzgzNDJm"

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD),
)

def generate_docs():
    with open("movies.json",encoding="utf8") as f:
        data = json.load(f)
        for row in data:
            doc = {
                    "_index": 'sample_dataset_2',
                    "_id": uuid.uuid4(),
                    "_source": row,
                }
            yield doc
    
helpers.bulk(client, generate_docs())
result = client.count(index='sample_dataset_2')
print(result)
